spring:
  application:
    name: microservice-customer

  data:
    mongodb:
      uri: mongodb+srv://mkmongouser:Secret_Password@cluster0.yu4x6.mongodb.net
      database: customer

server:
  port: 8080
  servlet:
    context-path: /customer